image: Visual Studio 2019

environment:
  NUGET_API_KEY:
    secure: 7v1kwlzMmeFtKQkZ7ws6ZqhuUinJiOKd6hz+H+PY/UqaQjxX195cLRBiU2swYSNS

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: |
    (& cmd /c); [console]::OutputEncoding = New-Object System.Text.UTF8Encoding;
    & .\build.ps1 --target AppVeyor_Pipeline --nuget-key "$($Env:NUGET_API_KEY)" --build-version git  --build-number $($Env:APPVEYOR_BUILD_NUMBER) --no-logo

test: off

artifacts:
- path: artifacts\*.nupkg
  name: NuGet

deploy: off
